version: '3.4'

services:
    # identity db (mysql)
    identity_db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=RootWiz@123
        volumes:
            - identity_data:/var/lib/mysql
        networks:
            - infrastructure
            
    # meeting db (mongodb)
    meeting_db_rs0:
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        command: mongod --replSet meeting-cluster-set
        networks:
            - infrastructure
        
    meeting_db_rs1:
        image: mongo
        ports:
            - "27018:27017"
        restart: always
        command: mongod --replSet meeting-cluster-set
        networks:
            - infrastructure
        
    meeting_db_rs2:
        image: mongo
        ports:
            - "27019:27017"
        restart: always
        command: mongod --replSet meeting-cluster-set
        networks:
            - infrastructure
        
    mongo_cluster_init:
        image: mongo
        restart: "no"
        depends_on:
            - meeting_db_rs0
            - meeting_db_rs1
            - meeting_db_rs2
        command: > 
            mongo --host meeting_db_rs0:27017 --eval
                '
                config = {
                    "_id" : "meeting-cluster-set",
                    "members" : [
                        {
                            "_id" : 0,
                            "host" : "meeting_db_rs0:27017"
                        },
                        {
                            "_id" : 1,
                            "host" : "meeting_db_rs1:27017"
                        },
                        {
                            "_id" : 2,
                            "host" : "meeting_db_rs2:27017"
                        }
                    ]
                };
                rs.initiate(config)
                '
        networks:
            - infrastructure
    
volumes:
    identity_data:
    
networks:
    infrastructure: {}