version: '3.4'

services:
    # identity db (mysql)
    identity_db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=RootWiz@123
        volumes:
            - identity_data:/var/lib/mysql
        networks:
            - wizbooking_infra

    # meeting db (mongodb)
    meeting_db_rs0:
        image: bitnami/mongodb
        extra_hosts:
            - "localhost:0.0.0.0"
        ports:
            - 27017:27017
        restart: always
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=meeting_db_rs0
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_REPLICA_SET_NAME=meeting_cluster
            - MONGODB_REPLICA_SET_KEY=abc123
            - MONGODB_ROOT_USER=root
            - MONGODB_ROOT_PASSWORD=rootDbForDev123
        volumes:
            - meeting_data:/data/db
        networks:
            - wizbooking_infra

volumes:
    identity_data:
    meeting_data:

networks:
    wizbooking_infra: