name: Docker

on:
  push:
    branches: ["master", "develop", "workflows-github"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  docker:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Setup checkout@v2
        uses: actions/checkout@v2

      - name: Infra dev
        working-directory: ${{ secrets.WORKING_DIR }}
        run: |
          chmod +x ./scripts/workflows/github-infra-dev.sh
          ./scripts/workflows/github-infra-dev.sh
        shell: bash
