name: Docker

on:
  push:
    branches: ["master", "develop", "workflows-github"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  docker:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Setup checkout@v2
        uses: actions/checkout@v2

      - name: Infra dev
        run: |
          chmod +x ./scripts/workflows-infra-dev.sh
          ./scripts/workflows-infra-dev.sh
        shell: bash
